/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'weli' at '3/18/17 9:03 PM' with Gradle 2.14.1
 *
 * @author weli, @date 3/18/17 9:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
